[general]
import = [
    "~/.config/alacritty/solarized_osaka.toml"
]

[env]
  TERM = "xterm-256color"

# Window Customization
[window]
padding = { x = 10, y = 10 }
opacity = 0.95
blur = true

[font]
size = 18.0
#
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"
#
[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"
#
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
#
[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" }
]

[mouse]
hide_when_typing = true

 bindings = [
      { mouse = "Back", mode="AppCursor|AppKeypad | Search | Alt | Vi", action = "None" },
      { mouse = "Left", mode="AppCursor|AppKeypad | Search | Alt | Vi", action = "None" },
      { mouse = "Forward", action = "None" },
      { mouse = "Right", action = "None" },
      { mouse = "Middle", action = "None" },
      { mouse = "Left", mods = "Control", action = "None" },
      { mouse = "Right", mods = "Control", action = "None" },
      { mouse = "Middle", mods = "Control", action = "None" },
 ]

